### ISSUE TITLE
Migrate CentOS builds to Rocky Linux (https://rockylinux.org/)

### ISSUE THREAD

**Issue by BenjamenMeyer** [vegastrike/build-system-docker-images#12]
**Is your feature request related to a problem? Please describe.**
Red Hat has discontinued CentOS and replaced it with a rolling distro (CentOS Stream); however the rolling distro is upstream of RH as opposed to it's historic downstream presence. Both these changes make it less than ideal to use as a base for building RH compatible builds.

**Describe the solution you'd like**
We need a good replacement for CentOS. Rocky Linux comes from the original creator of CentOS so while there are other potentials, Rocky Linux is probably the best as it aims to do what CentOS was doing before.

**Describe alternatives you've considered**
Any equivalent to the previous versions of CentOS series can be an alternative, but we should favor something that maintains that mission while being more community owned.

**Additional context**
N/A

**Comment by evertvorster** [comment]
Agreed
Evert Vorster
Awesome Chapters Tours
http://www.awesomechapters.com
Tel: +264 (0) 811477690

**Comment by stephengtuggy** [comment]
I agree as well.
