### ISSUE TITLE
Make the `bootstrap` script match between the Vega-Strike-Engine-Source and build-system-docker-images repos

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/build-system-docker-images#34]
**Is your feature request related to a problem? Please describe.**
Ever since I first created them, the `bootstrap` scripts have been out of sync between Vega-Strike-Engine-Source and build-system-docker-images. The build-system-docker-images version updates all packages on the entire system. The engine-source one does not, at least not on .deb-based distros. And the contents of these files are just slightly different.

**Describe the solution you'd like**
I would like to make the two files match by adding a parameter that controls whether or not to update all packages on the system to the latest available versions. Then in the engine-source repo, I would like to turn that parameter off, while in the docker-images repo, I would turn that parameter on, in order to mimic current behavior.

**Describe alternatives you've considered**
Leave the contents of the two files almost the same, but not quite. Frustrating and confusing.

**Additional context**
The difference is the presence or absence of the `apt-get -qy upgrade` command on Debian, Ubuntu, and Linux Mint distros.

**Comment by BenjamenMeyer** [comment]
yes, the Debian APT system allows for just updating packages that are installed easily; while the RPM tooling generally requires the whole system to get updated all the time.

Agreed the two functions should match up easily.
