### ISSUE TITLE
Move to GitHub Actions

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/build-system-docker-images#4]
Right now, this repo still uses Travis CI. We will need to migrate it to GitHub Actions before we can add more Docker build images.

**Comment by BenjamenMeyer** [comment]
We're using GitHub Actions for 0.7.x and need to forward port those changes to master (0.8.x) before we cut the 0.8.x branch.

**Comment by BenjamenMeyer** [comment]
put this in confirmation on release just to have a test period in case we find other issues. It's fine being closed.
