### ISSUE TITLE
Retire CentOS 8 builds

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/build-system-docker-images#9]
**Is your feature request related to a problem? Please describe.**
Sadly, CentOS 8 has bit the dust. Trying to build the corresponding Docker container fails now, and will probably continue to do so hereafter.

**Describe the solution you'd like**
We need to remove CentOS 8 from our Docker builds. Probably just comment it out for now.

**Describe alternatives you've considered**
There doesn't seem to be much choice but to retire CentOS builds. Although we may be able to replace them soon with another, similar RedHat-based OS.

**Additional context**
See discussions on linux subreddit, for example: https://www.reddit.com/r/CentOS/comments/k9goir/rip_centos_20042020/

**Comment by BenjamenMeyer** [comment]
I wonder if we can build using CentOS Stream...it's one possiblity, but we'll likely end up with a different RH-based distro.
